trigger:
  
  branches:
    include:
      - master

  tags:
    include:
      - v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'TTUserApplication'


stages:
  
  - stage: setVariableStage
    jobs:
      - job: setVariableJob
        steps:
          - script: |
              echo "Setting commitMessage variable"
              echo "##vso[task.setvariable variable=commitMessage;isOutput=true]$(Build.SourceVersionMessage)"
            name: commitMessageName
          - script: echo "The commitMessage is \"$(commitMessageName.commitMessage)\""
            name: echovar


  - stage: Build_QA_Dev
    displayName: Build_QA_Dev
    jobs:
      - job: Build_QA_Dev
        displayName: Build_QA_Dev
        variables:
          incrementNo: $[counter(format('{0:dd}', pipeline.startTime), 1)]
        steps:
          
          - script: |
              DATE=$(date '+%Y%m%d')
              echo $DATE
              echo "##vso[task.setvariable variable=CURRENT_DATE;isOutput=true]$DATE"
            name: SetDate


          - script: |
              
              MindSphereOSbar_appVersion=$(git describe --tags --abbrev=0)
              
              if [ -z "$MindSphereOSbar_appVersion" ]; then
                  MindSphereOSbar_appVersion=$(VersionTag2)
              fi
              
              echo $MindSphereOSbar_appVersion


              # echo "$(MindSphereOSbar_appVersion)_$(SetDate.CURRENT_DATE).$(incrementNo)" > $(Pipeline.Workspace)/buildtaginfo.txt
              # PR_Number= cat $(Pipeline.Workspace)/buildtaginfo.txt
              # echo $PR_Number
            displayName: 'Build Info tag'