trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'TTUserApplication'


steps:
- script: |
    MindSphereOSbar_appVersion=$(git describe --tags --abbrev=0)
    if [ -z "$MindSphereOSbar_appVersion" ]; then
        MindSphereOSbar_appVersion=$(VersionTag2)
    fi
    echo "$(MindSphereOSbar_appVersion)_$(SetDate.CURRENT_DATE).$(incrementNo)" > $(Pipeline.Workspace)/buildtaginfo.txt
    PR_Number= cat $(Pipeline.Workspace)/buildtaginfo.txt
    echo $PR_Number
  displayName: 'Build Info tag'